Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2022-10, with the labels that each got.

#34 #DP-117: added trainee invitation
  src/helpers/emailTemplate.helper.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/userResolver.ts
  src/schema/coordinator.schema.ts
  src/schema/index.ts
  src/utils/sendEmail.ts
  src/utils/templates/getOrganizationTemplate.ts
  src/utils/templates/inviteUserTemplate.ts
Labels: Ready for merge

#14 #DP-84 FT: Manage Ratings
  .env.example
  package-lock.json
  src/helpers/emailForTrainee.helper.ts
  src/helpers/emailTemplate.helper.ts
  src/index.ts
  src/models/ratings.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/profileResolver.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/seeders/cohorts.seed.ts
  src/seeders/organization.seed.ts
  src/seeders/users.seed.ts
  src/utils/sendEmail.ts
  src/utils/sendEmails.ts
  src/utils/validate-role.ts
Labels: Ready for merge

#38 #DP-123 Create backend review apps
  .github/workflows/review_app_close.yml
  .github/workflows/review_app_deploy.yml
  src/helpers/emailTemplate.helper.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/userResolver.ts
  src/utils/templates/inviteUserTemplate.ts
Labels: enhancement, Needs Reviews

#41 fix program and cohort dp-118
  .eslintrc.json
  .github/workflows/review_app_deploy.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  .travis.yml
  README.md
  custom.d.ts
  docker-compose.yml
  package-lock.json
  package.json
  src/ErrorMsg.ts
  src/database/db.config.ts
  src/helpers/emailForTrainee.helper.ts
  src/helpers/emailTemplate.helper.ts
  src/helpers/generateRandomPassword.ts
  src/helpers/organization.helper.ts
  src/helpers/user.helpers.ts
  src/index.ts
  src/models/cohort.model.ts
  src/models/program.model.ts
  src/models/ratingSystem.ts
  src/models/ratings.ts
  src/models/user.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/createRatingSystemresolver.ts
  src/resolvers/profileResolver.ts
  src/resolvers/program.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/resolver.ts
  src/resolvers/userResolver.ts
  src/schema/cohort.schema.ts
  src/schema/coordinator.schema.ts
  src/schema/index.ts
  src/schema/program.schema.ts
  src/seeders/cohorts.seed.ts
  src/seeders/index.ts
  src/seeders/organization.seed.ts
  src/seeders/programs.seed.ts
  src/seeders/users.seed.ts
  src/test/index.spec.ts
  src/utils/sendEmail.ts
  src/utils/sendEmails.ts
  src/utils/templates/getOrganizationTemplate.ts
  src/utils/templates/inviteUserTemplate.ts
  src/utils/templates/organizationCreatedTemplate.ts
  src/utils/templates/registrationRequestTemplate.ts
  src/utils/validate-role.ts
  src/utils/validation.utils.ts
  tsconfig.json
Labels: Ready for merge

#40 Fix profile issue
  src/models/user.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/seeders/organization.seed.ts
  src/seeders/profiles.seed.ts
  src/seeders/users.seed.ts
Labels: Needs Reviews

#43 bug(DP-109):Fixing Create rating system bug
  src/resolvers/createRatingSystemresolver.ts
  src/seeders/organization.seed.ts
Labels: Ready for merge, Top Priority

#42 Add profile fields on signup page
  .husky/pre-commit
  custom.d.ts
  src/ErrorMsg.ts
  src/context.ts
  src/helpers/emailForTrainee.helper.ts
  src/helpers/emailTemplate.helper.ts
  src/helpers/generateRandomPassword.ts
  src/helpers/organization.helper.ts
  src/helpers/user.helpers.ts
  src/index.ts
  src/models/cohort.model.ts
  src/models/program.model.ts
  src/models/ratings.ts
  src/models/user.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/createRatingSystemresolver.ts
  src/resolvers/profileResolver.ts
  src/resolvers/program.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/resolver.ts
  src/resolvers/userResolver.ts
  src/schema/cohort.schema.ts
  src/schema/coordinator.schema.ts
  src/schema/index.ts
  src/schema/program.schema.ts
  src/seeders/cohorts.seed.ts
  src/seeders/index.ts
  src/seeders/organization.seed.ts
  src/seeders/programs.seed.ts
  src/seeders/users.seed.ts
  src/test/index.spec.ts
  src/utils/sendEmail.ts
  src/utils/sendEmails.ts
  src/utils/templates/getOrganizationTemplate.ts
  src/utils/templates/inviteUserTemplate.ts
  src/utils/templates/organizationCreatedTemplate.ts
  src/utils/templates/registrationRequestTemplate.ts
  src/utils/validate-role.ts
  src/utils/validation.utils.ts
Labels: Ready for merge

#46 Sign up by invites
  src/helpers/organization.helper.ts
  src/models/user.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/utils/templates/inviteUserTemplate.ts
Labels: Ready for merge

#44 Fix issues on Manage ratings feature
  src/helpers/emailForTrainee.helper.ts
  src/helpers/emailTemplate.helper.ts
  src/models/ratings.ts
  src/resolvers/ratingsResolvers.ts
  src/schema/index.ts
  src/utils/sendEmails.ts
  src/utils/templates/inviteUserTemplate.ts
Labels: Needs Reviews

#54 Feedback on Programs and Cohorts
  .husky/pre-commit
  README.md
  src/helpers/emailForTrainee.helper.ts
  src/helpers/emailTemplate.helper.ts
  src/helpers/organization.helper.ts
  src/models/cohort.model.ts
  src/models/program.model.ts
  src/models/ratings.ts
  src/models/user.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/program.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/userResolver.ts
  src/schema/cohort.schema.ts
  src/schema/index.ts
  src/schema/program.schema.ts
  src/seeders/cohorts.seed.ts
  src/seeders/users.seed.ts
  src/utils/sendEmails.ts
  src/utils/templates/inviteUserTemplate.ts
Labels: Ready for merge

#50 ft(display): Display trainee in cohort
  .codeclimate.yml
  src/helpers/organization.helper.ts
  src/resolvers/coordinatorResolvers.ts
  src/schema/coordinator.schema.ts
  src/seeders/users.seed.ts
Labels: Needs Reviews

#53 fix(profile): update profile picture
  src/models/user.ts
  src/resolvers/profileResolver.ts
  src/schema/index.ts
Labels: Needs Reviews
