Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2023-11, with the labels that each got.

#198 fix retrieving and reply tickets on admin panel
  src/resolvers/attendance.resolvers.ts
  src/resolvers/ticket.resolver.ts
Labels: Needs Reviews

#202 Fixing create cohort
  src/resolvers/cohort.resolvers.ts
Labels: Needs Reviews, Ready for merge

#201 Super admin is able to create a new organization using an already existing admin email.
  Dockerfile
  src/resolvers/userResolver.ts
Labels: Ready for merge
