Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2023-07, with the labels that each got.

#98 #28-help-page Implement Help
  src/helpers/emailTemplate.helper.ts
  src/index.ts
  src/models/ticket.model.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/ticket.resolver.ts
  src/resolvers/userResolver.ts
  src/schema/ticket.shema.ts
Labels: Ready for merge

#97 Ft add ratings
  .prettierrc.json
  package-lock.json
  src/context.ts
  src/index.ts
  src/models/cohort.model.ts
  src/models/ratingSystem.ts
  src/models/ratings.ts
  src/models/team.model.ts
  src/models/user.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/createRatingSystemresolver.ts
  src/resolvers/notification.resolvers.ts
  src/resolvers/phase.resolver.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/reply.resolver.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/coordinator.schema.ts
  src/schema/index.ts
  src/seeders/index.ts
  src/seeders/phases.seed.ts
  src/seeders/rating.seed.ts
  src/seeders/ratingSystem.ts
  src/seeders/teams.seed.ts
  src/seeders/users.seed.ts
  src/utils/sendEmails.ts
  src/utils/validate-role.ts
Labels: Ready for merge

#101 Ch email migration
  .github/workflows/docker_image.yml
  package-lock.json
  package.json
  src/resolvers/userResolver.ts
  src/utils/sendEmail.ts
  src/utils/sendEmails.ts
Labels: Needs Reviews, ready for review

#100 Login activity
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/helpers/logintracker.ts
  src/models/user.ts
  src/resolvers/resolver.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
Labels: Needs Reviews
