Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2023-09, with the labels that each got.

#113 Ft TTLs Page
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/profileResolver.ts
  src/resolvers/userResolver.ts
  src/schema/coordinator.schema.ts
  src/schema/index.ts
  src/seeders/teams.seed.ts
  src/seeders/userRoles.seed.ts
Labels: Ready for merge

#149 fixing get trainees
  src/models/user.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/seeders/users.seed.ts
Labels: Ready for merge

#152 fix attendance scores calculation
  Dockerfile
  package-lock.json
  package.json
  src/resolvers/attendance.resolvers.ts
  src/seeders/users.seed.ts
Labels: Needs Reviews

#151 Fix-TTL-page
  src/resolvers/coordinatorResolvers.ts
Labels: ready for review
