Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2023-08, with the labels that each got.

#104 ft(manager-card) implementation of manager card
  Dockerfile
  src/models/team.model.ts
  src/models/user.ts
  src/resolvers/profileResolver.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/seeders/index.ts
  src/seeders/teams.seed.ts
  src/seeders/users.seed.ts
Labels: Ready for merge

#114 CRUD on grading system
  .gitignore
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/createRatingSystemresolver.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/userResolver.ts
  src/utils/sendEmail.ts
Labels: Ready for merge

#125 feat(case insensitive): devpulse orgname login (#225)
  package-lock.json
  package.json
  src/helpers/organization.helper.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
Labels: ready for review

#108 #ft-39-ticket-system-continued Add Reply Feature on Ticket System
  Dockerfile
  src/database/db.config.ts
  src/index.ts
  src/models/ticket.model.ts
  src/models/user.ts
  src/resolvers/notification.resolvers.ts
  src/resolvers/ticket.resolver.ts
  src/schema/ticket.shema.ts
  src/seeders/index.ts
  src/seeders/ticket.seed.ts
Labels: ready for review

#127 Ft docs implementation
  package-lock.json
  src/index.ts
  src/models/documentation.model.ts
  src/models/user.ts
  src/resolvers/DocumentationResolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
Labels: Needs Reviews

#110 feat:Upload resume
  Dockerfile
  package.json
  src/models/user.ts
  src/resolvers/profileResolver.ts
  src/schema/index.ts
Labels: ready for review
