Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2024-10, with the labels that each got.

#332 Mobile Reset Password
  src/resolvers/userResolver.ts
  src/utils/templates/forgotPasswordTemplate.ts
Labels: enhancement, Needs Reviews, ready for review

#316 fx(filtering): Fixing filtering on table
  .gitignore
  src/resolvers/TableViewInvitationResolver.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/schema/invitation.schema.ts
Labels: Needs Reviews, fighters

#333 Remove logging token
  src/utils/logGraphQLRequests.ts
Labels: ready for review, fighters

#335 admin should be able to resend pending invitations
  src/resolvers/invitation.resolvers.ts
  src/schema/invitation.schema.ts
Labels: fighters

#334 event tokens for confirmation
  .env.example
  src/helpers/sendEventEmails.ts
  src/resolvers/eventResolver.ts
  src/schema/event.schema.ts
  src/utils/templates/eventInvitationTemplates.ts
Labels: Ready for merge, Nova

#329 #233 refactors and implement attendance functionality
  package-lock.json
  package.json
  src/models/attendance.model.ts
  src/models/cohort.model.ts
  src/models/phase.model.ts
  src/models/team.model.ts
  src/models/user.ts
  src/resolvers/attendance.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/phase.resolver.ts
  src/schema/index.ts
  src/seeders/index.ts
Labels: ready for review, steppers

#342 #340 Send Email to invitees when an Event is updated
  src/helpers/sendEventEmails.ts
  src/resolvers/eventResolver.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/utils/templates/eventInvitationTemplates.ts
Labels: Needs Reviews, Nova

#339 #326 fx-remove duplicate codes by using code helper
  src/helpers/user.helpers.ts
  src/models/invitation.model.ts
  src/models/user.ts
  src/resolvers/attendance.resolvers.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/createRatingSystemresolver.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/notification.resolvers.ts
  src/resolvers/phase.resolver.ts
  src/resolvers/profileResolver.ts
  src/resolvers/program.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/reply.resolver.ts
  src/resolvers/resolver.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/ticket.resolver.ts
  src/resolvers/userResolver.ts
  src/seeders/attendance.seed.ts
  src/seeders/cohorts.seed.ts
  src/seeders/organization.seed.ts
  src/seeders/programs.seed.ts
  src/seeders/ticket.seed.ts
  src/seeders/userRoles.seed.ts
  src/seeders/users.seed.ts
  src/utils/extractFileData.ts
Labels: ready for review, Nova

#343 Fix password reset link
  src/helpers/generateInvitationToken.helper.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/userResolver.ts
Labels: ready for review

#341 Fix all CRUD operations of tickets
  src/helpers/sendEventEmails.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/resolvers/ticket.resolver.ts
  src/schema/ticket.shema.ts
  src/utils/sendEmail.ts
  src/utils/templates/eventInvitationTemplates.ts
Labels: Ready for merge

#336 adding undrop trainee feature
  src/context.ts
  src/models/user.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/coordinator.schema.ts
  src/seeders/users.seed.ts
Labels: Needs Reviews, steppers

#351 fix(profile): fixes getProfile query
  src/resolvers/profileResolver.ts
Labels: bug, Ready for merge, steppers

#347 Fixing fetching github activity
  src/resolvers/userResolver.ts
Labels: bug, ready for review, Nova

#346 fix-update-attendance
  src/resolvers/attendance.resolvers.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/phase.resolver.ts
  src/resolvers/userResolver.ts
Labels: enhancement, ready for review, steppers

#368 fix Organization login
  src/context.ts
  src/helpers/user.helpers.ts
Labels: bug, Needs Reviews, Nova

#337 #331 Improve invitation table pagination to be dynamic
  src/resolvers/TableViewInvitationResolver.ts
Labels: ready for review, fighters

#369 #577 Add Role on invitation Email
  src/helpers/sendInvitaitonEmail.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/invitation.resolvers.ts
  src/utils/capitalizeRoleName.ts
  src/utils/templates/inviteUserTemplate.ts
  src/utils/templates/updateInvitationTemplate.ts
Labels: Needs Reviews, fighters

#367 #581 sort invitations
  src/resolvers/TableViewInvitationResolver.ts
  src/schema/invitation.schema.ts
Labels: Needs Reviews, fighters

#365 fix-update-docs
  src/resolvers/DocumentationResolvers.ts
  src/resolvers/ticket.resolver.ts
  src/utils/templates/eventInvitationTemplates.ts
Labels: Needs Reviews, steppers

#362 #579 Admin should be able to login after signup
  src/resolvers/userResolver.ts
Labels: Needs Reviews, fighters

#364 Fix login activities 404
  package-lock.json
  package.json
  src/index.ts
  src/models/profile.model.ts
  src/resolvers/profileResolver.ts
  src/resolvers/resolver.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/utils/capitalizeRoleName.ts
  src/utils/templates/inviteUserTemplate.ts
  src/utils/templates/updateInvitationTemplate.ts
Labels: Needs Reviews, Nova

#373 fix remove exposed tokens secrete
  src/context.ts
  src/helpers/generateInvitationToken.helper.ts
  src/helpers/organization.helper.ts
  src/helpers/sendEventEmails.ts
  src/helpers/sendInvitaitonEmail.ts
  src/helpers/user.helpers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/resolver.ts
  src/resolvers/userResolver.ts
Labels: ready for review, Nova

#371 #378 Fix on the dynamic pagination on the invitations
  src/resolvers/TableViewInvitationResolver.ts
Labels: ready for review, fighters

#379 #374 implement fetch trainees such that any admin can see all trainees
  src/resolvers/coordinatorResolvers.ts
Labels: Needs Reviews, fighters

#380 #395 Fix: Login as superadmin
  src/resolvers/userResolver.ts
Labels: Needs Reviews, fighters

#396 #391 Enable Consistent Edit For All Cohorts
  src/resolvers/cohort.resolvers.ts
  src/schema/cohort.schema.ts
Labels: fighters

#376 fix(#404): Getting the Client's Ip Adress using request_ip package
  package-lock.json
  package.json
  src/context.ts
  src/resolvers/userResolver.ts
Labels: bug, Needs Reviews, Nova

#404 #604 Improve Cohort Visibility for New Admins
  package-lock.json
  src/resolvers/cohort.resolvers.ts
  src/seeders/cohorts.seed.ts
Labels: ready for review, fighters

#405 #393 Allow coordinator to add trainees
  src/resolvers/coordinatorResolvers.ts
Labels: Needs Reviews, fighters
