Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2024-09, with the labels that each got.

#247 #430 invitations Email Template
  package-lock.json
  src/helpers/emailTemplate.helper.ts
  src/index.ts
  src/utils/templates/inviteUserTemplate.ts
  src/utils/templates/ratingTemplate.ts
  src/utils/templates/surveyTemplate.ts
Labels: ready for review, fighters

#248 #421 Invite user by role and email
  package-lock.json
  src/index.ts
  src/models/invitation.model.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/invitation.schema.ts
Labels: Needs Reviews, ready for review, fighters

#249 #246 migrate ApolloServer to v4
  .env.example
  package-lock.json
  package.json
  src/ErrorMsg.ts
  src/context.ts
  src/helpers/organization.helper.ts
  src/helpers/user.helpers.ts
  src/index.ts
  src/resolvers/DocumentationResolvers.ts
  src/resolvers/attendance.resolvers.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/phase.resolver.ts
  src/resolvers/program.resolvers.ts
  src/resolvers/reply.resolver.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/ticket.resolver.ts
  src/resolvers/userResolver.ts
  src/schema/cohort.schema.ts
  src/schema/coordinator.schema.ts
  src/schema/index.ts
  src/schema/invitation.schema.ts
  src/schema/phase.schema.ts
  src/schema/program.schema.ts
  src/schema/ticket.shema.ts
  src/seeders/users.seed.ts
  src/test/index.spec.ts
Labels: Ready for merge, Nova

#251 #424 in-app and email notifications for ratings
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/helpers/emailTemplate.helper.ts
  src/index.ts
  src/models/attendance.model.ts
  src/models/notification.model.ts
  src/models/organization.model.ts
  src/models/profile.model.ts
  src/resolvers/notification.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/session.resolver.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/schema/notification.schema.ts
  src/utils/logGraphQLRequests.ts
  src/utils/notifications/pushNotification.ts
  src/utils/templates/inviteUserTemplate.ts
  src/utils/templates/ratingTemplate.ts
  src/utils/templates/surveyTemplate.ts
Labels: ready for review, steppers

#263 #425 Ft trainee attendance notifications
  package-lock.json
  src/index.ts
  src/models/notification.model.ts
  src/models/reply.model.ts
  src/resolvers/attendance.resolvers.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/team.resolvers.ts
  src/seeders/users.seed.ts
  src/utils/notification/pushNotification.ts
  src/utils/sendEmails.ts
Labels: Ready for merge, ready for review, steppers

#258 #428 Fix trainees notification
  package-lock.json
  src/models/ratings.ts
  src/models/reply.model.ts
  src/models/user.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/profileResolver.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/reply.resolver.ts
  src/resolvers/resolver.ts
  src/resolvers/team.resolvers.ts
  src/schema/index.ts
  src/seeders/cohorts.seed.ts
  src/seeders/phases.seed.ts
  src/seeders/teams.seed.ts
  src/utils/notification/pushNotification.ts
  src/utils/sendEmail.ts
  src/utils/sendEmails.ts
  src/utils/templates/dropTraineeTemplate.ts
  src/utils/templates/removeTraineeTamplete.ts
Labels: ready for review, steppers

#259 #426 implement coordinator notification
  package-lock.json
  src/models/notification.model.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/notification.resolvers.ts
  src/resolvers/team.resolvers.ts
  src/schema/notification.schema.ts
  src/utils/notification/pushNotification.ts
  src/utils/notifications/pushNotification.ts
  src/utils/sendEmails.ts
Labels: Ready for merge, steppers

#262 #441 TTL Notifications
  .vscode/settings.json
  package-lock.json
  package.json
  src/index.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/team.resolvers.ts
Labels: Ready for merge, steppers

#257 #432 Invite users using an excel file
  package-lock.json
  package.json
  src/helpers/sendInvitaitonEmail.ts
  src/index.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/invitation.schema.ts
  src/utils/extractFileData.ts
Labels: ready for review, fighters

#270 #433 invitation statistics
  src/index.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/schema/invitationStatics.schema.ts
Labels: Ready for merge, fighters

#275 #419 Admin paginated Invitation table view PR
  src/index.ts
  src/resolvers/TableViewInvitationResolver.ts
  src/schema/invitation.schema.ts
Labels: Needs Reviews, Ready for merge, ready for review, fighters

#284 #474 Restricting new registed user to be redirected…
  src/resolvers/userResolver.ts
Labels: ready for review, fighters

#267 Fix admin notification
  src/index.ts
  src/models/notification.model.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/notification.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/session.resolver.ts
  src/schema/notification.schema.ts
  src/utils/notification/pushNotification.ts
Labels: WIP, ready for review, steppers

#283 fix invitation by excel file,duplicating
  src/resolvers/invitation.resolvers.ts
Labels: Ready for merge, ready for review, fighters

#289 #289 filter Invitation statistics based on different time ranges
  src/resolvers/invitationStatics.resolvers.ts
  src/schema/invitationStatics.schema.ts
Labels: Ready for merge, ready for review, fighters

#292 #279 Update user's invitation
  src/helpers/generateInvitationToken.helper.ts
  src/helpers/sendInvitaitonEmail.ts
  src/models/invitation.model.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/invitation.schema.ts
  src/utils/templates/updateInvitationTemplate.ts
Labels: Ready for merge, ready for review, fighters

#294 fix-get-trainee-organisation
  src/resolvers/userResolver.ts
Labels: ready for review, steppers

#291 #274 fix trainees login without cohort
  src/resolvers/userResolver.ts
Labels: ready for review, Nova

#297 #477 improving invitation filter
  src/resolvers/TableViewInvitationResolver.ts
  src/schema/invitation.schema.ts
  src/seeders/users.seed.ts
Labels: Needs Reviews, Ready for merge, fighters

#298 Fix allowing Ttl to rate
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/profileResolver.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/userResolver.ts
  src/utils/templates/updateInvitationTemplate.ts
Labels: Needs Reviews, Ready for merge, steppers

#299 fix new registerd user restriction
  src/helpers/isAssignedToProgramOrCohort.ts
  src/resolvers/TableViewInvitationResolver.ts
  src/resolvers/userResolver.ts
Labels: Needs Reviews, fighters

#288 #469 Admin Should be able to cancel a sent invitation
  src/helpers/cancelInvitationEmail.ts
  src/helpers/sendInvitaitonEmail.ts
  src/models/invitation.model.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/schema/invitation.schema.ts
  src/schema/invitationStatics.schema.ts
  src/utils/templates/cancelInvitationTemplate.ts
Labels: Needs Reviews, Nova

#301 #477 improving invitation filter
  src/resolvers/TableViewInvitationResolver.ts
Labels: Needs Reviews, Ready for merge, Top Priority, ready for review, fighters

#307 Fix allowing both ttl and coordinator rating trainee
  src/helpers/isAssignedToProgramOrCohort.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/userResolver.ts
  src/utils/validate-role.ts
Labels: Needs Reviews, steppers

#304 fix get invitation based on user who loges in
  src/helpers/isAssignedToProgramOrCohort.ts
  src/resolvers/TableViewInvitationResolver.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/resolvers/userResolver.ts
Labels: Needs Reviews, Ready for merge, fighters

#306 #260 fix approve on organisation
  src/resolvers/userResolver.ts
Labels: bug, Ready for merge, Nova

#308 #469 Fix on Getting Cancel Invitation Statistics
  src/resolvers/invitation.resolvers.ts
Labels: Ready for merge, Nova, fighters

#313 Fix invitation filter based on time range.
  src/models/invitation.model.ts
  src/resolvers/TableViewInvitationResolver.ts
  src/resolvers/invitation.resolvers.ts
  src/resolvers/invitationStatics.resolvers.ts
  src/schema/invitation.schema.ts
Labels: Needs Reviews, fighters

#295 fix-admin-update-team-info
  src/helpers/logintracker.ts
  src/models/team.model.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
Labels: Ready for merge, Nova

#287 #242-CRUD Operations for tickets
  package-lock.json
  package.json
  src/models/ticket.model.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/ticket.resolver.ts
  src/schema/ticket.shema.ts
  src/seeders/index.ts
  src/seeders/ticket.seed.ts
  src/seeders/users.seed.ts
Labels: Ready for merge, steppers

#309 email display
  src/resolvers/userResolver.ts
Labels: bug, Ready for merge, Nova

#290 #238 Improve calendar functionality
  src/helpers/sendEventEmails.ts
  src/index.ts
  src/models/event.model.ts
  src/resolvers/eventResolver.ts
  src/schema/event.schema.ts
  src/schema/index.ts
  src/utils/templates/eventInvitationTemplates.ts
Labels: Ready for merge, Nova
