Repository atlp-rwanda/atlp-pulse-bn, pull requests merged in 2024-11, with the labels that each got.

#370 #417 Add bulk rating
  src/resolvers/cohort.resolvers.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/team.resolvers.ts
  src/schema/cohort.schema.ts
  src/schema/index.ts
  src/utils/sheets/extractSheetRatings.ts
Labels: Ready for merge, Nova

#358 #357 Refactor attendance handling to be processed server-side
  package-lock.json
  package.json
  src/index.ts
  src/models/attendance.model.ts
  src/models/team.model.ts
  src/models/user.ts
  src/resolvers/attendance.resolvers.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/utils/cron-jobs/team-jobs.ts
  src/utils/getDateForDays.ts
Labels: ready for review, steppers

#383 Ft-TTL-page
  src/resolvers/profileResolver.ts
  src/schema/index.ts
Labels: Needs Reviews, ready for review, steppers

#403 #392 Limit TTL to only of One Team Assignment
  src/resolvers/team.resolvers.ts
Labels: Needs Reviews, fighters

#395 #318 Add request approve link to org email
  src/helpers/user.helpers.ts
  src/resolvers/userResolver.ts
  src/utils/templates/registrationRequestTemplate.ts
Labels: ready for review, fighters

#385 Fix trainee attendance
  src/resolvers/attendance.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/seeders/users.seed.ts
Labels: Needs Reviews, steppers

#411 #410 Refactoring Codebase
  src/models/profile.model.ts
  src/models/user.ts
  src/schema/index.ts
Labels: Needs Reviews

#414 #408: Coordinator can remove trainee
  src/resolvers/coordinatorResolvers.ts
Labels: Needs Reviews, fighters

#413 #273: Add timestamps for all models
  src/models/cohort.model.ts
  src/models/event.model.ts
  src/models/invitation.model.ts
  src/models/organization.model.ts
  src/models/phase.model.ts
  src/models/profile.model.ts
  src/models/program.model.ts
  src/models/ratingSystem.ts
  src/models/session.model.ts
  src/models/team.model.ts
  src/models/user.ts
Labels: Needs Reviews, fighters

#420 implement superAdmin dashboard
  src/index.ts
  src/models/organization.model.ts
  src/models/user.ts
  src/resolvers/eventResolver.ts
  src/resolvers/organization.resolvers.ts
  src/resolvers/ticket.resolver.ts
  src/resolvers/userResolver.ts
  src/schema/organization.schema.ts
  src/utils/cron-jobs/team-jobs.ts
Labels: Ready for merge, steppers

#426 # 409: Sending an email corresponding to the action done when a trainee is added to a cohort
  src/resolvers/coordinatorResolvers.ts
  src/utils/templates/getOrganizationTemplate.ts
Labels: fighters

#407 Implementing 2 Factor Authentication
  src/index.ts
  src/models/user.ts
  src/resolvers/2fa.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/utils/2WayAuthentication.ts
Labels: enhancement, Needs Reviews, Nova

#412 #461 creating a community page
  .eslintrc.json
  package-lock.json
  package.json
  src/helpers/user.helpers.ts
  src/index.ts
  src/models/question.model.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/community.resolver.ts
  src/resolvers/profileResolver.ts
  src/resolvers/ratingsResolvers.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/community.schema.ts
  src/utils/sheets/extractSheetRatings.ts
  tsconfig.json
Labels: Needs Reviews, ready for review, steppers

#432 fix-coordinator-table
  src/models/cohort.model.ts
  src/resolvers/2fa.resolvers.ts
  src/resolvers/cohort.resolvers.ts
  src/resolvers/coordinatorResolvers.ts
  src/resolvers/team.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/utils/2WayAuthentication.ts
Labels: ready for review, steppers

#433 #431: Non-trainee-invitations
  src/resolvers/userResolver.ts
  src/utils/templates/nonTraineeTemplate.ts
Labels: Ready for merge, fighters

#434 #630: Implement the contact us form submission
  src/helpers/sendForm.ts
  src/index.ts
  src/resolvers/contactus.resolver.ts
  src/schema/contactus.schema.ts
  src/utils/templates/contactFormTemplate.ts
Labels: Needs Reviews, fighters

#435 #325 fix:updating env.example
  .env.example
Labels: Needs Reviews, fighters

#344 Test coverage enhancement
  package.json
  src/test/attendance.spec.ts
  src/test/cohorts.spec.ts
  src/test/coordinator.spec.ts
  src/test/createRating.spec.ts
  src/test/documentation.spec.ts
  src/test/event.spec.ts
  src/test/invitation.spec.ts
  src/test/notification.spec.ts
  src/test/phase.spec.ts
  src/test/profile.spec.ts
  src/test/ratings.spec.ts
  src/test/resolver.spec.ts
  src/test/tableViewInvitation.spec.ts
  src/test/team.spec.ts
  src/test/ticket.spec.ts
  src/test/user.spec.ts
Labels: Ready for merge, Nova

#437 fixing login with 2fa
  src/models/user.ts
  src/resolvers/2fa.resolvers.ts
  src/resolvers/userResolver.ts
  src/schema/index.ts
  src/utils/2WayAuthentication.ts
Labels: bug, Needs Reviews, Nova

#427 fix(#418): solving unusual suspicious email
  src/helpers/logintracker.ts
Labels: Ready for merge, Nova

#440 ft admin dashboard: Add Time user joined to an Organisation
  src/resolvers/profileResolver.ts
  src/schema/index.ts
Labels: Ready for merge
